myproject/urls.py
from django.contrib import admin
from django.urls import path,include
 

urlpatterns = [
    path('',include('rto.urls',namespace='rto')),
    path('admin/', admin.site.urls),
    
]

rto/urls.py
from django.urls import path,re_path

from . import views
app_name = 'rto'
urlpatterns = [
    path('', views.home, name='home'),
    path('find',views.findCity,name='findCity'),
    # path('add',views.addCity,name='addCity'),
    path('findall',views.findAll,name='findAll'),
    re_path('^.*$',views.showError , name="showError")
]

rto/models.py
from django.db import models

# Create your models here.

class RTOCode(models.Model):
    state_name = models.CharField(max_length=2)
    #  some sectors have 02A like city_codes
    city_code = models.CharField(max_length=4)
    city_name = models.CharField(max_length=100)

    def __str__(self):
        return self.state_name + ' - ' +str(self.city_code) + ' ==> ' + str(self.city_name)

rto/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse
from .models import RTOCode
from django.template import loader
# Create your views here.


def home(request):
    template = loader.get_template('rto/input.html')
    context = {}
    return HttpResponse(template.render(context, request))


def findCity(request):
    try : 
        state_name = request.POST['state_name'].upper()
        city_code = request.POST['city_code'].lstrip('0')
        print("State Name:",state_name)
        print("City Code:",city_code)
        obj_list = RTOCode.objects.filter(state_name=state_name).filter(city_code=city_code)
        print(obj_list)
        response = "Result : "
        if len(obj_list) != 0 :
            obj_list= obj_list.values()[0]
            response += "Object Found with the State Name = "+state_name + " , and City Code : "+ city_code + " <br></br>  <h2>"+ str(obj_list["city_name"]) +"</h2>"
        else:
            response += "No Object Found with the State Name = "+state_name + " , and City Code : "+ city_code
        return HttpResponse(response)
    except (RTOCode.DoesNotExist,KeyError,Exception) as err:
        return render(request,'rto/input.html',{'error_message':'Error in Form  '+str(err)})

def addCityToDB(state_name, city_code,city_name):
    try:
        city_objects = RTOCode.objects.create(state_name=state_name, city_code=city_code,city_name=city_name)
        city_objects.save()
        return 200
    except Exception as err:
        print("Exception: "+err)
        return 400


# use this  url when you need to add data to Database from rto_Codes.csv
def addCity(request):
    try : 
        import pandas as pd 
        af = pd.read_csv('/home/RakshitKathawate/rto-code-app/rto_codes.csv')
        # af = af.head()

        for idx, row in af.iterrows():
            state_name= row.state_name.upper()
            city_code = row.city_code.lstrip('0')
            city_name = row.city_name
            
            print("State Name:",state_name)
            print("City Code:",city_code)
            print("CityName : ",city_name)
            if addCityToDB(state_name=state_name, city_code=city_code,city_name=city_name) == 200 :
                pass
            else : 
                print("Sorry !!, something went wrong ")
        return HttpResponse ('Successfully added Data !!!')
    except Exception as err:
        return HttpResponse('Error Obtained: '+str(err))

def findAll(request):

    obj_list= RTOCode.objects.all().order_by('state_name','city_code')
    # response = " , ".join([str(obj) for obj in obj_list])
    context= {'rto_codes':obj_list}
    return render(request,'rto/show.html',context)


def showError(request):

    # any errors there, show alert and redirect to home page
    return redirect("/")

rto/templates/rto/input.html
<h1> GET the City Name from RTO Code  !!! </h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'rto:findCity'%}" method="post">
{% csrf_token %}
<label for="state_name">State name :</label>
<input pattern="[a-zA-Z]+" oninvalid ="alert('Please enter Alphabets only');" type="text" id="state_name" name="state_name"><br><br>

<label for="city_code">City Code:</label>
<input type="text" id="city_code" name="city_code"><br><br>

<!-- <label for="city_name">City Name:</label>
<input type="text" id="city_name" name="city_name"><br><br> -->

<input type="submit" value="Find">
</form>

rto/templates/rto/show.html
<!DOCTYPE html> 
<html lang="en"> 
<head> 
  <title>All RTO Codes and City Names</title> 
  <meta charset="utf-8"> 
  <meta name="viewport" content="width=device-width, initial-scale=1"> 
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css"> 
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script> 
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script> 
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"></script> 
</head> 
<body> 
  
<div class="container"> 
  <h2 class="text-center"><u> RTO Table </u></h2><br>             
  <table class="table table-dark table-striped"> 
    <thead> 
      <tr> 
        <th>State Name  </th> 
        <th>City Code</th> 
        <th>City Name</th> 
      </tr> 
    </thead> 
    <tbody> 
    <!-- jinja2 Technique -->
    {% if rto_codes %}   
    {% for rto in rto_codes %} 
      <tr> 
        <td>{{rto.state_name}}</td> 
        <td>{{rto.city_code}}</td> 
        <td>{{rto.city_name}}</td> 
      </tr> 
    {% endfor %} 
    {% endif %} 
    </tbody> 
  </table> 
</div> 
  
</body> 
</html>